(deftheme leuven-high-contrast
  "Fix leuven")

(custom-theme-set-variables
 'leuven-high-contrast
 '(hl-sexp-background-color "#efebe9"))

(custom-theme-set-faces
 'leuven-high-contrast
 '(bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(bold-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "black"))))
 '(italic ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(cursor ((((class color) (min-colors 89)) (:background "#21BDFF"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#FFFFFF" :background "#333333"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#4C9ED9" :background "white"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#E6ECFF"))))
 '(region ((((class color) (min-colors 89)) (:background "#8ED3FF"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(isearch ((((class color) (min-colors 89)) (:underline "black" :foreground "white" :background "#5974AB"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FFCCCC"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFF00"))))
 '(trailing-whitespace ((t (:background "#F4D7DA" :foreground "#E8E8E8"))))
 '(query-replace ((((class color) (min-colors 89)) (:inherit isearch))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:foreground "#D2D2D2"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "white"))))
 '(whitespace-line ((((class color) (min-colors 89)) (:foreground "#CC0000" :background "#FFFF88"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:foreground "#E8E8E8" :background "white"))))
 '(whitespace-trailing ((t (:background "#F4D7DA" :foreground "#E8E8E8"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#1A2F54") :foreground "#85CEEB" :background "#335EA8"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#4E4E4C") :foreground "#F0F0EF" :background "#9B9C97"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:foreground "dark orange"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "gold"))))
 '(minibuffer-noticeable-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "gold"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#008ED1"))))
 '(error ((((class color) (min-colors 89)) (:foreground "red"))))
 '(warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(success ((((class color) (min-colors 89)) (:foreground "green"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#006FE0"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8D8D84"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#8D8D84"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#036A07"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006699"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#0000FF"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:weight bold :inherit nil))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:weight normal :foreground "#6434A3"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:weight normal :foreground "#BA36A5"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(link-visited ((((class color) (min-colors 89)) (:underline t :foreground "#E5786D"))))
 '(button ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(header-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color "black") :foreground "black" :background "#F0F0F0"))))
 '(gnus-button ((((class color) (min-colors 89)) (:weight normal))))
 '(gnus-cite-attribution-face ((((class color) (min-colors 89)) (:foreground "#5050B0"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#5050B0" :background "#F6F6F6"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#660066" :background "#F6F6F6"))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:foreground "#007777" :background "#F6F6F6"))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:foreground "#990000" :background "#F6F6F6"))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:foreground "#000099" :background "#F6F6F6"))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:foreground "#BB6600" :background "#F6F6F6"))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:foreground "#5050B0" :background "#F6F6F6"))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:foreground "#660066" :background "#F6F6F6"))))
 '(gnus-cite-9 ((((class color) (min-colors 89)) (:foreground "#007777" :background "#F6F6F6"))))
 '(gnus-cite-10 ((((class color) (min-colors 89)) (:foreground "#990000" :background "#F6F6F6"))))
 '(gnus-emphasis-bold ((((class color) (min-colors 89)) (:weight bold))))
 '(gnus-emphasis-highlight-words ((((class color) (min-colors 89)) (:foreground "yellow" :background "black"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF50B0"))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:foreground "#5050B0"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF0066"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:foreground "#660066"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#000000"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:foreground "#8C8C8C"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#A9A9A9"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#A9A9A9"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF50B0"))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#5050B0"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF0066"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#660066"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#000000"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#8C8C8C"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF0000"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#990000"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#FF0099"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#000099"))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :foreground "gray50"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "black"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#A3A3A2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#3399CC"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "black"))))
 '(gnus-picon ((((class color) (min-colors 89)) (:foreground "yellow" :background "white"))))
 '(gnus-picon-xbm ((((class color) (min-colors 89)) (:foreground "yellow" :background "white"))))
 '(gnus-server-closed ((((class color) (min-colors 89)) (:slant italic :foreground "blue" :background "white"))))
 '(gnus-server-denied ((((class color) (min-colors 89)) (:weight bold :foreground "red" :background "white"))))
 '(gnus-server-opened ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "white" :foreground "#466BD7"))))
 '(gnus-signature ((((class color) (min-colors 89)) (:slant italic :foreground "#8B8D8E"))))
 '(gnus-splash ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:slant italic :strike-through t :foreground "#A9A9A9"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:weight bold :foreground "#135985"))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#FF3300"))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:weight bold :foreground "#135985"))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:slant italic :foreground "black"))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:slant italic :foreground "#999999" :background "#E0E0E0"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#FF3300"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:slant italic :foreground "black"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#8C8C8C"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#8C8C8C"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#FF3300"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:weight bold :foreground "#000000"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "white" :background "#008CD7"))))
 '(gnus-x-face ((((class color) (min-colors 89)) (:foreground "black" :background "white"))))
 '(message-header-name ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#A3A3A2"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-header-other ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:family "Sans Serif" :weight bold :foreground "black"))))
 '(message-header-to ((((class color) (min-colors 89)) (:family "Sans Serif" :underline nil :foreground "#006DAF"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#5050B0" :background "#F6F6F6"))))
 '(message-separator ((((class color) (min-colors 89)) (:family "Sans Serif" :weight normal :foreground "#BDC2C6"))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:family "Sans Serif" :foreground "#3399CC"))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:family "Sans Serif" :slant normal :foreground "#666666"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "forest green"))))
 '(ansi-color-bold ((((class color) (min-colors 89)) (:weight bold))))
 '(ansi-color-black ((((class color) (min-colors 89)) (:foreground "black" :background "black"))))
 '(ansi-color-red ((((class color) (min-colors 89)) (:foreground "red3" :background "red3"))))
 '(ansi-color-green ((((class color) (min-colors 89)) (:foreground "forest green" :background "forest green"))))
 '(ansi-color-yellow ((((class color) (min-colors 89)) (:foreground "yellow3" :background "yellow3"))))
 '(ansi-color-blue ((((class color) (min-colors 89)) (:foreground "blue" :background "blue"))))
 '(ansi-color-magenta ((((class color) (min-colors 89)) (:foreground "magenta3" :background "magenta3"))))
 '(ansi-color-cyan ((((class color) (min-colors 89)) (:foreground "deep sky blue" :background "deep sky blue"))))
 '(ansi-color-white ((((class color) (min-colors 89)) (:foreground "gray60" :background "gray60"))))
 '(ansi-color-bright-black ((((class color) (min-colors 89)) (:foreground "gray30" :background "gray30"))))
 '(ansi-color-bright-red ((((class color) (min-colors 89)) (:foreground "red1" :background "red1"))))
 '(ansi-color-bright-green ((((class color) (min-colors 89)) (:foreground "lime green" :background "lime green"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 89)) (:foreground "yellow2" :background "yellow2"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 89)) (:foreground "dodger blue" :background "dodger blue"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 89)) (:foreground "magenta" :background "magenta"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 89)) (:foreground "sky blue" :background "sky blue"))))
 '(ansi-color-bright-white ((((class color) (min-colors 89)) (:foreground "gray80" :background "gray80"))))
 '(diff-added ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#0000FF" :background "#DDDDFF"))))
 '(diff-context ((((class color) (min-colors 89)) (:foreground "#888888"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-file1-hunk-header ((((class color) (min-colors 89)) (:foreground "dark magenta" :background "#EAF2F5"))))
 '(diff-file2-hunk-header ((((class color) (min-colors 89)) (:foreground "#2B7E2A" :background "#EAF2F5"))))
 '(diff-function ((((class color) (min-colors 89)) (:foreground "#CC99CC"))))
 '(diff-header ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#990099" :background "#FFEEFF"))))
 '(diff-index ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(diff-indicator-added ((((class color) (min-colors 89)) (:foreground "#3A993A" :background "#CDFFD8"))))
 '(diff-indicator-changed ((((class color) (min-colors 89)) (:background "#DBEDFF"))))
 '(diff-indicator-removed ((((class color) (min-colors 89)) (:foreground "#CC3333" :background "#FFDCE0"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:background "#97F295"))))
 '(diff-refine-change ((((class color) (min-colors 89)) (:background "#DDDDFF"))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:background "#FFB6BA"))))
 '(diff-removed ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(smerge-upper ((((class color) (min-colors 89)) (:foreground "#0000FF" :background "#DDDDFF"))))
 '(smerge-lower ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(smerge-base ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(smerge-markers ((((class color) (min-colors 89)) (:background "#FFE5CC"))))
 '(smerge-refined-changed ((((class color) (min-colors 89)) (:background "#AAAAFF"))))
 '(ediff-current-diff-A ((((class color) (min-colors 89)) (:background "#FFDDDD"))))
 '(ediff-current-diff-B ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "cyan"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "light grey"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "light grey"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#FFAAAA"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#55FF55"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "light grey"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "light grey"))))
 '(flyspell-duplicate ((((class color) (min-colors 89)) (:underline (:style wave :color "#F4EB80") :background "#FAF7CC" :inherit nil))))
 '(flyspell-incorrect ((((class color) (min-colors 89)) (:underline (:style wave :color "#FAA7A5") :background "#F4D7DA" :inherit nil))))
 '(semantic-decoration-on-unknown-includes ((((class color) (min-colors 89)) (:background "#FFF8F8"))))
 '(semantic-highlight-func-current-tag-face ((((class color) (min-colors 89)) (:background "#E8E8FF"))))
 '(semantic-tag-boundary-face ((((class color) (min-colors 89)) (:overline "#777777"))))
 '(Info-title-1-face ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(Info-title-2-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(Info-title-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(Info-title-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(ace-jump-face-foreground ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FEA500"))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#E4E4FF"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:background "#FFB6C6"))))
 '(ahs-plugin-defalt-face ((((class color) (min-colors 89)) (:background "#FFE4FF"))))
 '(anzu-match-1 ((((class color) (min-colors 89)) (:foreground "black" :background "aquamarine"))))
 '(anzu-match-2 ((((class color) (min-colors 89)) (:foreground "black" :background "springgreen"))))
 '(anzu-match-3 ((((class color) (min-colors 89)) (:foreground "black" :background "red"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "black" :background "#80FF80"))))
 '(anzu-mode-line-no-match ((((class color) (min-colors 89)) (:foreground "black" :background "#FF8080"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit query-replace))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:weight bold :foreground "#BD33FD" :background "#FDBD33"))))
 '(auto-dim-other-buffers-face ((((class color) (min-colors 89)) (:background "#F7F7F7"))))
 '(avy-background-face ((((class color) (min-colors 89)) (:background "#A9A9A9"))))
 '(avy-lead-face ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FEA500"))))
 '(bbdb-company ((((class color) (min-colors 89)) (:slant italic :foreground "steel blue"))))
 '(bbdb-field-name ((((class color) (min-colors 89)) (:weight bold :foreground "steel blue"))))
 '(bbdb-field-value ((((class color) (min-colors 89)) (:foreground "steel blue"))))
 '(bbdb-name ((((class color) (min-colors 89)) (:underline t :foreground "#FF6633"))))
 '(bmkp-light-autonamed ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(bmkp-light-fringe-autonamed ((((class color) (min-colors 89)) (:foreground "#5A5A5A" :background "#D4D4D4"))))
 '(bmkp-light-fringe-non-autonamed ((((class color) (min-colors 89)) (:foreground "#FFFFCC" :background "#01FFFB"))))
 '(bmkp-light-non-autonamed ((((class color) (min-colors 89)) (:background "#BFFFFE"))))
 '(bmkp-no-local ((((class color) (min-colors 89)) (:background "pink"))))
 '(browse-kill-ring-separator-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(calendar-month-header ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(calendar-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(calendar-weekday-header ((((class color) (min-colors 89)) (:weight bold :foreground "#1662AF"))))
 '(calendar-weekend-header ((((class color) (min-colors 89)) (:weight bold :foreground "#4E4E4E"))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:foreground "green" :background "red"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:foreground "#C9C9C9"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#2952A3"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:foreground "DarkGray"))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#DDDDDD"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#1662AF" :background "white" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:foreground "#777777" :background "#E4EBFE"))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "white" :background "#668CD9" :slant italic))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#4E4E4E" :background "white" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:foreground "#4A95EB" :background "#EDF1FA"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#4E4E4E" :background "white" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:height 2.0 :foreground "#676767" :weight bold :inherit variable-pitch))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:foreground "#4F4A3D" :background "#FFFFCC"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:foreground "white" :background "#1766B1"))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "white"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:foreground "#CFCFCF" :background "white"))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:foreground "#5E5E5E" :background "#F6F6F6"))))
 '(change-log-date ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(change-log-file ((((class color) (min-colors 89)) (:weight bold :foreground "#4183C4"))))
 '(change-log-list ((((class color) (min-colors 89)) (:foreground "black" :background "#75EEC7"))))
 '(change-log-name ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(circe-highlight-all-nicks-face ((((class color) (min-colors 89)) (:foreground "blue" :background "#F0F0F0"))))
 '(circe-highlight-nick-face ((((class color) (min-colors 89)) (:foreground "#009300" :background "#F0F0F0"))))
 '(circe-my-message-face ((((class color) (min-colors 89)) (:foreground "#8B8B8B" :background "#F0F0F0"))))
 '(circe-originator-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(circe-prompt-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(circe-server-face ((((class color) (min-colors 89)) (:foreground "#99CAE5"))))
 '(comint-highlight-input ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(comint-highlight-prompt ((((class color) (min-colors 89)) (:weight bold :foreground "#0000FF" :inherit nil))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "orange"))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#EBF4FE"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:weight normal :foreground "#C0C0C0" :inherit hl-line))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#EBF4FE"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#D1DAE4"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#F9ECCC" :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#0052A4"))))
 '(company-tooltip-annotation-selection ((((class color) (min-colors 89)) (:weight normal :foreground "#F9ECCC"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :foreground "#B000B0" :inherit company-tooltip))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#EBF4FE"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#2415FF"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:weight normal :foreground "#C0C0C0" :inherit hl-line))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#EBF4FE"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#D1DAE4"))))
 '(compare-windows-added ((((class color) (min-colors 89)) (:background "#FFFF00"))))
 '(compilation-error ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(compilation-info ((((class color) (min-colors 89)) (:weight bold :foreground "#6784d7"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:weight bold :foreground "#A535AE"))))
 '(compilation-warning ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:weight bold :foreground "green"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:weight bold :foreground "violet"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(css-property ((((class color) (min-colors 89)) (:foreground "#00AA00"))))
 '(css-selector ((((class color) (min-colors 89)) (:weight bold :foreground "blue"))))
 '(custom-button ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "lightgrey"))))
 '(custom-button-mouse ((((class color) (min-colors 89)) (:box (:line-width 2 :style released-button) :foreground "black" :background "grey90"))))
 '(custom-button-pressed ((((class color) (min-colors 89)) (:box (:line-width 2 :style pressed-button) :foreground "black" :background "light grey"))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(custom-button-unraised ((((class color) (min-colors 89)) (:underline t))))
 '(custom-changed ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-comment ((((class color) (min-colors 89)) (:background "gray85"))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(custom-documentation ((((class color) (min-colors 89)) (nil))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:height 1.2 :weight bold :foreground "blue1"))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "red1"))))
 '(custom-invalid ((((class color) (min-colors 89)) (:foreground "yellow" :background "red"))))
 '(custom-link ((((class color) (min-colors 89)) (:underline t :foreground "blue1"))))
 '(custom-modified ((((class color) (min-colors 89)) (:foreground "white" :background "blue"))))
 '(custom-rogue ((((class color) (min-colors 89)) (:foreground "pink" :background "black"))))
 '(custom-saved ((((class color) (min-colors 89)) (:underline t))))
 '(custom-set ((((class color) (min-colors 89)) (:foreground "blue" :background "white"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(custom-themed ((((class color) (min-colors 89)) (:foreground "white" :background "blue1"))))
 '(custom-variable-button ((((class color) (min-colors 89)) (:weight bold :underline t))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.2 :weight bold :foreground "blue1"))))
 '(custom-visibility ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:foreground "blue3" :background "#DBEDFF"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:foreground "red3" :background "#FFDCE0"))))
 '(diff-hl-dired-change ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#FFA335"))))
 '(diff-hl-dired-delete ((((class color) (min-colors 89)) (:weight bold :foreground "#D73915"))))
 '(diff-hl-dired-ignored ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#C0BBAB"))))
 '(diff-hl-dired-insert ((((class color) (min-colors 89)) (:weight bold :foreground "#B9B9BA"))))
 '(diff-hl-dired-unknown ((((class color) (min-colors 89)) (:foreground "white" :background "#3F3BB4"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:foreground "green4" :background "#CDFFD8"))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) (:foreground "white" :background "#3F3BB4"))))
 '(diary-face ((((class color) (min-colors 89)) (:foreground "#87C9FC"))))
 '(dircolors-face-asm ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-backup ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-compress ((((class color) (min-colors 89)) (:foreground "red"))))
 '(dircolors-face-dir ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dircolors-face-doc ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-dos ((((class color) (min-colors 89)) (:foreground "ForestGreen"))))
 '(dircolors-face-emacs ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-exec ((((class color) (min-colors 89)) (:foreground "ForestGreen"))))
 '(dircolors-face-html ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-img ((((class color) (min-colors 89)) (:foreground "magenta3"))))
 '(dircolors-face-lang ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-lang-interface ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-make ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-objet ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-package ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-paddb ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-ps ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-sound ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue"))))
 '(dircolors-face-tar ((((class color) (min-colors 89)) (:foreground "red"))))
 '(dircolors-face-text ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dircolors-face-yacc ((((class color) (min-colors 89)) (:foreground "black"))))
 '(dired-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dired-header ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:strike-through t :foreground "red"))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#1F8DD6"))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "red"))))
 '(diredp-date-time ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(diredp-dir-name ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:background "#03C03C"))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "ForestGreen" :background "white"))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "black"))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "#C0C0C0"))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:background "#0A99FF"))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "white" :background "#FF4040"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:weight bold :foreground "red" :background "#FFE4FF"))))
 '(elfeed-search-filter-face ((((class color) (min-colors 89)) (:foreground "gray"))))
 '(eww-form-text ((((class color) (min-colors 89)) (:weight bold :foreground "#40586F" :background "#A7CDF1"))))
 '(file-name-shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:color "#FE251E" :style wave) :weight bold :background "#FFE1E1"))))
 '(flycheck-error-list-line-number ((((class color) (min-colors 89)) (:foreground "#A535AE"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#FE251E"))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#158A15"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#F4A939"))))
 '(flycheck-info ((((class color) (min-colors 89)) (:underline (:color "#158A15" :style wave) :weight bold))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:color "#F4A939" :style wave) :weight bold :background "#FFFFBE"))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(fancy-narrow-blocked-face ((((class color) (min-colors 89)) (:foreground "#9998A4"))))
 '(flycheck-color-mode-line-error-face ((((class color) (min-colors 89)) (:background "#CF5B56"))))
 '(flycheck-color-mode-line-warning-face ((((class color) (min-colors 89)) (:background "#EBC700"))))
 '(flycheck-color-mode-line-info-face ((((class color) (min-colors 89)) (:background "yellow"))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "#1A1A1A"))))
 '(font-latex-math-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:family "Sans Serif" :height 2.7 :weight bold :foreground "cornflower blue"))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(font-latex-sedate-face ((((class color) (min-colors 89)) (:foreground "#FF5500"))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:weight bold :foreground "#0066FF"))))
 '(font-latex-verbatim-face ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0" :inherit nil))))
 '(git-commit-summary-face ((((class color) (min-colors 89)) (:foreground "#000000"))))
 '(git-commit-comment-face ((((class color) (min-colors 89)) (:slant italic :foreground "#696969"))))
 '(git-timemachine-commit ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(git-timemachine-minibuffer-author-face ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(git-timemachine-minibuffer-detail-face ((((class color) (min-colors 89)) (:weight bold :foreground "#800000" :background "#FFFFAF"))))
 '(google-translate-text-face ((((class color) (min-colors 89)) (:foreground "#777777" :background "#F5F5F5"))))
 '(google-translate-phonetic-face ((((class color) (min-colors 89)) (:inherit shadow))))
 '(google-translate-translation-face ((((class color) (min-colors 89)) (:weight normal :foreground "#3079ED" :background "#E3EAF2"))))
 '(google-translate-suggestion-label-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(google-translate-suggestion-face ((((class color) (min-colors 89)) (:slant italic :underline t))))
 '(google-translate-listen-button-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(helm-action ((((class color) (min-colors 89)) (:foreground "black"))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "black"))))
 '(helm-bookmarks-su-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(helm-buffer-modified ((((class color) (min-colors 89)) (:slant italic :foreground "#BA36A5"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#008200"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFF66"))))
 '(helm-dir-heading ((((class color) (min-colors 89)) (:foreground "blue" :background "pink"))))
 '(helm-dir-priv ((((class color) (min-colors 89)) (:foreground "dark red" :background "light grey"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "green3" :background "white"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "black"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "yellow" :background "red"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#1F8DD6"))))
 '(helm-file-name ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(helm-gentoo-match-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:weight bold :foreground "#2A489E"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:weight bold :foreground "#A535AE"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(helm-grep-running ((((class color) (min-colors 89)) (:weight bold :foreground "white"))))
 '(helm-isearch-match ((((class color) (min-colors 89)) (:background "#CCFFCC"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:height 1.1 :underline nil :foreground "white" :background "#9E3699"))))
 '(helm-ls-git-modified-not-staged-face ((((class color) (min-colors 89)) (:foreground "#BA36A5"))))
 '(helm-match ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#0066CC"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#3875D6" :foreground "white"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#E4E4E3"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "red"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#C7C7C7") :background "#DEDEDE" :foreground "black"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 89)) (:background "#CCCC00" :foreground "#222222"))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 89)) (:background "#CCCCFF"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 89)) (:weight bold :foreground nil :background "#FDBD33"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(helm-w3m-bookmarks-face ((((class color) (min-colors 89)) (:underline t :foreground "cyan1"))))
 '(highlight-changes ((((class color) (min-colors 89)) (:foreground nil))))
 '(highlight-changes-delete ((((class color) (min-colors 89)) (:strike-through nil :foreground nil))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#FFFFA0"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#F6FECD"))))
 '(hl-tags-face ((((class color) (min-colors 89)) (:background "#E8E8FF"))))
 '(holiday-face ((((class color) (min-colors 89)) (:foreground "#777777" :background "#E4EBFE"))))
 '(html-helper-bold-face ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(html-helper-italic-face ((((class color) (min-colors 89)) (:slant italic :foreground "black"))))
 '(html-helper-underline-face ((((class color) (min-colors 89)) (:underline t :foreground "black"))))
 '(html-tag-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(ilog-non-change-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#6434A3"))))
 '(ilog-change-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#008200"))))
 '(ilog-echo-face ((((class color) (min-colors 89)) (:height 2.0 :foreground "#006FE0"))))
 '(ilog-load-face ((((class color) (min-colors 89)) (:foreground "#BA36A5"))))
 '(ilog-message-face ((((class color) (min-colors 89)) (:foreground "#808080"))))
 '(indent-guide-face ((((class color) (min-colors 89)) (:foreground "#D3D3D3"))))
 '(info-file ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.8 :weight bold :box (:line-width 1 :color "#0000CC") :foreground "cornflower blue" :background "LightSteelBlue1"))))
 '(info-header-node ((((class color) (min-colors 89)) (:underline t :foreground "orange"))))
 '(info-header-xref ((((class color) (min-colors 89)) (:underline t :foreground "dodger blue"))))
 '(info-index-match ((((class color) (min-colors 89)) (:weight bold :foreground nil :background "#FDBD33"))))
 '(info-menu-header ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(info-menu-star ((t (:foreground "red"))))
 '(info-node ((((class color) (min-colors 89)) (:underline t :foreground "blue"))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7"))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#008000"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(info-xref ((((class color) (min-colors 89)) (:underline t :foreground "#006DAF"))))
 '(info-xref-visited ((((class color) (min-colors 89)) (:underline t :foreground "magenta4"))))
 '(js2-error ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#FF3737") :background "#FFC8C8"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#FF0000" :background "#FFF8F8"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#247284"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "DarkOrchid"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#D0372D"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:weight normal :foreground "#6434A3"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "SteelBlue"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:weight normal :foreground "#BA36A5"))))
 '(js2-magic-paren ((((class color) (min-colors 89)) (:underline t))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "PeachPuff3"))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "orange"))))
 '(leuven-org-deadline-overdue ((((class color) (min-colors 89)) (:foreground "#F22659"))))
 '(leuven-org-deadline-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(leuven-org-deadline-tomorrow ((((class color) (min-colors 89)) (:foreground "#40A80B"))))
 '(leuven-org-deadline-future ((((class color) (min-colors 89)) (:foreground "#40A80B"))))
 '(leuven-gnus-unseen ((((class color) (min-colors 89)) (:weight bold :foreground "#FC7202"))))
 '(leuven-gnus-date ((((class color) (min-colors 89)) (:foreground "#FF80BF"))))
 '(leuven-gnus-size ((((class color) (min-colors 89)) (:foreground "#8FBF60"))))
 '(leuven-todo-items-face ((((class color) (min-colors 89)) (:weight bold :foreground "#FF3125" :background "#FFFF88"))))
 '(light-symbol-face ((((class color) (min-colors 89)) (:background "#FFFFA0"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#9A9A9A" :background "#EDEDED"))))
 '(log-view-file ((((class color) (min-colors 89)) (:foreground "#0000CC" :background "#EAF2F5"))))
 '(log-view-message ((((class color) (min-colors 89)) (:foreground "black" :background "#EDEA74"))))
 '(lsp-ui-doc-background ((((class color) (min-colors 89)) (:background "#F6FECD"))))
 '(lui-button-face ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(lui-highlight-face ((((class color) (min-colors 89)) (:box '(:line-width 1 :color "#CC0000") :foreground "#CC0000" :background "#FFFF88"))))
 '(lui-time-stamp-face ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(magit-blame-header ((((class color) (min-colors 89)) (:inherit magit-diff-file-header))))
 '(magit-blame-heading ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "red" :background "#E6E6E6"))))
 '(magit-blame-hash ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "red" :background "#E6E6E6"))))
 '(magit-blame-name ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "#036A07" :background "#E6E6E6"))))
 '(magit-blame-date ((((class color) (min-colors 89)) (:overline "#A7A7A7" :foreground "blue" :background "#E6E6E6"))))
 '(magit-blame-summary ((((class color) (min-colors 89)) (:overline "#A7A7A7" :weight bold :foreground "#707070" :background "#E6E6E6"))))
 '(magit-branch ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#00CC33") :foreground "black" :background "#AAFFAA"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:background "#DDFFDD"))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:background "#FEE8E9"))))
 '(magit-diff-file-header ((((class color) (min-colors 89)) (:height 1.1 :weight bold :foreground "#4183C4"))))
 '(magit-diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#990099" :background "#FFEEFF"))))
 '(magit-diff-none ((((class color) (min-colors 89)) (:foreground "#888888"))))
 '(magit-header ((((class color) (min-colors 89)) (:foreground "white" :background "#FF4040"))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#EAF2F5"))))
 '(magit-item-mark ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(magit-log-head-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "blue" :style nil)))))
 '(magit-log-tag-label ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#00CC00" :style nil)))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#F6FECD"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:family "Sans Serif" :height 1.8 :weight bold :foreground "cornflower blue" :inherit nil))))
 '(makefile-space-face ((((class color) (min-colors 89)) (:background "hot pink"))))
 '(makefile-targets ((((class color) (min-colors 89)) (:weight bold :foreground "blue"))))
 '(markdown-bold-face ((((class color) (min-colors 89)) (:inherit bold))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D"))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC"))))
 '(markdown-inline-code-face ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7"))))
 '(markdown-italic-face ((((class color) (min-colors 89)) (:inherit italic))))
 '(markdown-language-keyword-face ((((class color) (min-colors 89)) (:inherit org-block-begin-line))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:weight normal :foreground "#006DAF"))))
 '(markdown-pre-face ((((class color) (min-colors 89)) (:inherit org-block-background))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(match ((((class color) (min-colors 89)) (:weight bold :background "#FFFF00"))))
 '(mc/cursor-bar-face ((((class color) (min-colors 89)) (:height 1.0 :foreground "#1664C4" :background "#1664C4"))))
 '(mc/cursor-face ((((class color) (min-colors 89)) (:inverse-video t))))
 '(mc/region-face ((((class color) (min-colors 89)) (:inherit region))))
 '(mm-uu-extract ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0"))))
 '(moccur-current-line-face ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFFCC"))))
 '(moccur-face ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFF99"))))
 '(next-error ((((class color) (min-colors 89)) (:height 1.1 :underline nil :foreground "white" :background "#9E3699"))))
 '(nobreak-space ((((class color) (min-colors 89)) (:background "#CCE8F6"))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground "#F36335"))))
 '(nxml-attribute-value-delimiter-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(nxml-attribute-value-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(nxml-comment-content-face ((((class color) (min-colors 89)) (:slant italic :foreground "red"))))
 '(nxml-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "red"))))
 '(nxml-element-local-name ((((class color) (min-colors 89)) (:foreground "#AE1B9A"))))
 '(nxml-element-local-name-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(nxml-processing-instruction-target-face ((((class color) (min-colors 89)) (:foreground "purple1"))))
 '(nxml-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(nxml-tag-slash-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(org-agenda-block-count ((((class color) (min-colors 89)) (:weight bold :foreground "#A5A5A5"))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:weight bold :foreground "#3774CC" :background "#E4EBFE"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#327ACD" :background "#F3F7FC"))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:foreground "black" :background "#EEC900"))))
 '(org-agenda-column-dateline ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-agenda-current-time ((((class color) (min-colors 89)) (:underline t :foreground "#1662AF"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#1662AF"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#4E4E4E"))))
 '(org-agenda-diary ((((class color) (min-colors 89)) (:weight bold :foreground "green4" :background "light blue"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "gold2"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#555555"))))
 '(org-agenda-filter-category ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-effort ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-regexp ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-filter-tags ((((class color) (min-colors 89)) (:weight bold :foreground "orange"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#E77D63"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:height 1.6 :weight bold :foreground "#1F8DD6"))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "gray70"))))
 '(org-beamer-tag ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#FABC18") :foreground "#2C2C2C" :background "#FFF8D0"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#000088" :background "#FFFFE0"))))
 '(org-block-background ((((class color) (min-colors 89)) (:background "#FFFFE0"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:underline "#A7A6AA" :foreground "#555555" :background "#E2E1D5"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:overline "#A7A6AA" :foreground "#555555" :background "#E2E1D5"))))
 '(org-checkbox ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :style pressed-button) :foreground "#123555" :background "#A3A3A3"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "white" :background "SkyBlue4"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#006400" :background "#FDFFF7"))))
 '(org-column ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-column-title ((((class color) (min-colors 89)) (:height 1.0 :weight normal :slant normal :underline nil :strike-through nil :foreground "#E6AD4F" :background "#FFF2DE"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#00459E"))))
 '(org-default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF"))))
 '(org-dim ((((class color) (min-colors 89)) (:foreground "#AAAAAA"))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#484848"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#008ED1" :background "#EAEAFF"))))
 '(org-document-title ((((class color) (min-colors 89)) (:height 1.8 :weight bold :foreground "black"))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#BBBBBB") :foreground "#BBBBBB" :background "#F0F0F0"))))
 '(org-drawer ((((class color) (min-colors 89)) (:weight bold :foreground "#00BB00" :background "#EAFFEA" :extend nil))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:underline nil :foreground "#999999"))))
 '(org-example ((((class color) (min-colors 89)) (:foreground "blue" :background "#EAFFEA"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#008ED1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "chocolate1"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:height 1.0 :weight normal :foreground "#ADADAD"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#E2E2E2"))))
 '(org-inlinetask ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#EBEBEB") :foreground "#777777" :background "#FFFFD6"))))
 '(org-latex-and-related ((((class color) (min-colors 89)) (:foreground "#336699" :background "white"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008"))))
 '(org-link ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(org-list-dt ((((class color) (min-colors 89)) (:weight bold :foreground "#335EA8"))))
 '(org-macro ((((class color) (min-colors 89)) (:weight bold :foreground "#EDB802"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:slant normal :foreground "#008ED1" :background "#EAEAFF"))))
 '(org-mode-line-clock ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#335EA8") :foreground "black" :background "#FFA335"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#335EA8") :foreground "white" :background "#FF4040"))))
 '(org-number-of-items ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "#79BA79"))))
 '(org-property-value ((((class color) (min-colors 89)) (:foreground "#00A000"))))
 '(org-quote ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#FFFFE0"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#333333"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#1466C6"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4F4A3D" :background "#FFFFCC"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#3774CC"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:weight bold :foreground "#00BB00" :background "#EAFFEA"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "dark green" :background "#EAFFEA"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight normal :slant italic :foreground "#9A9FA4" :background "white"))))
 '(org-target ((((class color) (min-colors 89)) (:foreground "#FF6DAF"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#CFCFCF"))))
 '(org-todo ((((class color) (min-colors 89)) (:weight bold :box (:line-width 1 :color "#D8ABA7") :foreground "#D8ABA7" :background "#FFE6E4"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#FF5555"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#0066CC" :background "#F7FDFF"))))
 '(org-verse ((((class color) (min-colors 89)) (:slant italic :foreground "dim gray" :background "#EEEEEE"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "black" :background "#CCE7FF"))))
 '(outline-1 ((((class color) (min-colors 89)) (:height 1.3 :weight bold :overline "#A7A7A7" :foreground "#3C3C3C" :background "#F0F0F0"))))
 '(outline-2 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :overline "#123555" :foreground "#123555" :background "#E5F4FB"))))
 '(outline-3 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :foreground "#005522" :background "#EFFFEF"))))
 '(outline-4 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#EA6300"))))
 '(outline-5 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant normal :foreground "#E3258D"))))
 '(outline-6 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#0077CC"))))
 '(outline-7 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#2EAE2C"))))
 '(outline-8 ((((class color) (min-colors 89)) (:height 1.0 :weight bold :slant italic :foreground "#FD8008"))))
 '(pabbrev-debug-display-label-face ((((class color) (min-colors 89)) (:foreground "white" :background "#A62154"))))
 '(pabbrev-suggestions-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "red"))))
 '(pabbrev-suggestions-label-face ((((class color) (min-colors 89)) (:weight bold :foreground "white" :background "purple"))))
 '(paren-face-match ((((class color) (min-colors 89)) (:background "#C0E8C3"))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(persp-selected-face ((((class color) (min-colors 89)) (:weight bold :foreground "#EEF5FE"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:foreground "#85CEEB" :background "#383838" :inherit mode-line))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:foreground "#85CEEB" :background "#4070B6" :inherit mode-line))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:foreground "#F0F0EF" :background "#686868" :inherit mode-line-inactive))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:foreground "#F0F0EF" :background "#A9A9A9" :inherit mode-line-inactive))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#707183"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#7388D6"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#909183"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#709870"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#907373"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#6276BA"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#858580"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#80A880"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#887070"))))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(recover-this-file ((((class color) (min-colors 89)) (:weight bold :background "#FF3F3F"))))
 '(rng-error ((((class color) (min-colors 89)) (:weight bold :foreground "red" :background "#FBE3E4"))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "blue" :background "#EEF5FE"))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#7F7F7F"))))
 '(shell-option-face ((((class color) (min-colors 89)) (:foreground "forest green"))))
 '(shell-output-2-face ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(shell-output-3-face ((((class color) (min-colors 89)) (:foreground "purple"))))
 '(shell-output-face ((((class color) (min-colors 89)) (:foreground "black"))))
 '(shm-current-face ((((class color) (min-colors 89)) (:background "#EEE8D5"))))
 '(shm-quarantine-face ((((class color) (min-colors 89)) (:background "lemonchiffon"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#C0E8C3"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:weight bold :underline "red" :foreground "black" :background "#FFA5A5"))))
 '(sml-modeline-end-face ((((class color) (min-colors 89)) (:background "#6BADF6"))))
 '(sml-modeline-vis-face ((((class color) (min-colors 89)) (:background "#1979CA"))))
 '(term ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:foreground "blue4"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:foreground "cyan4"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:underline nil :foreground "white" :background "#9E3699"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:underline t :foreground "red"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:foreground "brown"))))
 '(svn-status-directory-face ((((class color) (min-colors 89)) (:weight bold :foreground "blue" :background "#FFFFD2"))))
 '(svn-status-filename-face ((((class color) (min-colors 89)) (:weight bold :foreground "#4183C4"))))
 '(svn-status-locked-face ((((class color) (min-colors 89)) (:weight bold :foreground "red"))))
 '(svn-status-marked-face ((((class color) (min-colors 89)) (:foreground "#AA0000" :background "#FFAAAA"))))
 '(svn-status-marked-popup-face ((((class color) (min-colors 89)) (:weight bold :foreground "green3"))))
 '(svn-status-switched-face ((((class color) (min-colors 89)) (:slant italic :foreground "gray55"))))
 '(svn-status-symlink-face ((((class color) (min-colors 89)) (:foreground "#1F8DD6"))))
 '(svn-status-update-available-face ((((class color) (min-colors 89)) (:foreground "orange"))))
 '(tex-verbatim ((((class color) (min-colors 89)) (:foreground "blue"))))
 '(tool-bar ((((class color) (min-colors 89)) (:box (:line-width 1 :style released-button) :foreground "black" :background "gray75"))))
 '(tooltip ((((class color) (min-colors 89)) (:foreground "black" :background "light yellow"))))
 '(traverse-match-face ((((class color) (min-colors 89)) (:weight bold :foreground "blue violet"))))
 '(vc-annotate-face-3F3FFF ((((class color) (min-colors 89)) (:foreground "#3F3FFF" :background "black"))))
 '(vc-annotate-face-3F6CFF ((((class color) (min-colors 89)) (:foreground "#3F3FFF" :background "black"))))
 '(vc-annotate-face-3F99FF ((((class color) (min-colors 89)) (:foreground "#3F99FF" :background "black"))))
 '(vc-annotate-face-3FC6FF ((((class color) (min-colors 89)) (:foreground "#3F99FF" :background "black"))))
 '(vc-annotate-face-3FF3FF ((((class color) (min-colors 89)) (:foreground "#3FF3FF" :background "black"))))
 '(vc-annotate-face-3FFF56 ((((class color) (min-colors 89)) (:foreground "#4BFF4B" :background "black"))))
 '(vc-annotate-face-3FFF83 ((((class color) (min-colors 89)) (:foreground "#3FFFB0" :background "black"))))
 '(vc-annotate-face-3FFFB0 ((((class color) (min-colors 89)) (:foreground "#3FFFB0" :background "black"))))
 '(vc-annotate-face-3FFFDD ((((class color) (min-colors 89)) (:foreground "#3FF3FF" :background "black"))))
 '(vc-annotate-face-56FF3F ((((class color) (min-colors 89)) (:foreground "#4BFF4B" :background "black"))))
 '(vc-annotate-face-83FF3F ((((class color) (min-colors 89)) (:foreground "#B0FF3F" :background "black"))))
 '(vc-annotate-face-B0FF3F ((((class color) (min-colors 89)) (:foreground "#B0FF3F" :background "black"))))
 '(vc-annotate-face-DDFF3F ((((class color) (min-colors 89)) (:foreground "#FFF33F" :background "black"))))
 '(vc-annotate-face-F6FFCC ((((class color) (min-colors 89)) (:foreground "black" :background "#FFFFC0"))))
 '(vc-annotate-face-FF3F3F ((((class color) (min-colors 89)) (:foreground "#FF3F3F" :background "black"))))
 '(vc-annotate-face-FF6C3F ((((class color) (min-colors 89)) (:foreground "#FF3F3F" :background "black"))))
 '(vc-annotate-face-FF993F ((((class color) (min-colors 89)) (:foreground "#FF993F" :background "black"))))
 '(vc-annotate-face-FFC63F ((((class color) (min-colors 89)) (:foreground "#FF993F" :background "black"))))
 '(vc-annotate-face-FFF33F ((((class color) (min-colors 89)) (:foreground "#FFF33F" :background "black"))))
 '(vhl/default-face ((((class color) (min-colors 89)) (:underline nil :foreground "white" :background "#9E3699"))))
 '(w3m-anchor ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(w3m-arrived-anchor ((((class color) (min-colors 89)) (:foreground "purple1"))))
 '(w3m-bitmap-image-face ((((class color) (min-colors 89)) (:foreground "gray4" :background "green"))))
 '(w3m-bold ((((class color) (min-colors 89)) (:weight bold :foreground "black"))))
 '(w3m-current-anchor ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "blue"))))
 '(w3m-form ((((class color) (min-colors 89)) (:underline t :foreground "tan1"))))
 '(w3m-form-button-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "gray4" :background "light grey"))))
 '(w3m-form-button-mouse-face ((((class color) (min-colors 89)) (:underline t :foreground "light grey" :background "#2B7E2A"))))
 '(w3m-form-button-pressed-face ((((class color) (min-colors 89)) (:weight bold :underline t :foreground "gray4" :background "light grey"))))
 '(w3m-header-line-location-content-face ((((class color) (min-colors 89)) (:foreground "#7F7F7F" :background "#F7F7F7"))))
 '(w3m-header-line-location-title-face ((((class color) (min-colors 89)) (:foreground "#2C55B1" :background "#F7F7F7"))))
 '(w3m-history-current-url-face ((((class color) (min-colors 89)) (:foreground "lemon chiffon"))))
 '(w3m-image-face ((((class color) (min-colors 89)) (:weight bold :foreground "DarkSeaGreen2"))))
 '(w3m-link-numbering ((((class color) (min-colors 89)) (:foreground "#B4C7EB"))))
 '(w3m-strike-through-face ((((class color) (min-colors 89)) (:strike-through t))))
 '(w3m-underline-face ((((class color) (min-colors 89)) (:underline t))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:background "#99CCFF"))))
 '(web-mode-folded-face ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#777777") :foreground "#9A9A6A" :background "#F3F349"))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#F36335"))))
 '(web-mode-html-tag-bracket-face ((((class color) (min-colors 89)) (:foreground "#AE1B9A"))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#AE1B9A"))))
 '(web-mode-part-face ((((class color) (min-colors 89)) (:background "#FFFFE0"))))
 '(web-mode-script-face ((((class color) (min-colors 89)) (:background "#EFF0F1"))))
 '(which-func ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "white"))))
 '(which-key-local-map-description-face ((((class color) (min-colors 89)) (:weight bold :background "#F3F7FC" :inherit which-key-command-description-face))))
 '(widget-button ((((class color) (min-colors 89)) (:weight normal :underline t :foreground "#006DAF"))))
 '(widget-button-pressed ((((class color) (min-colors 89)) (:foreground "red"))))
 '(widget-documentation ((((class color) (min-colors 89)) (:foreground "green4"))))
 '(widget-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(widget-inactive ((((class color) (min-colors 89)) (:foreground "dim gray"))))
 '(widget-single-line-field ((((class color) (min-colors 89)) (:background "gray85"))))
 '(woman-bold ((((class color) (min-colors 89)) (:weight bold :foreground "#F13D3D"))))
 '(woman-italic ((((class color) (min-colors 89)) (:weight bold :slant italic :foreground "#46BE1B"))))
 '(woman-symbol ((((class color) (min-colors 89)) (:weight bold :foreground "purple"))))
 '(yas-field-debug-face ((((class color) (min-colors 89)) (:foreground "white" :background "#A62154"))))
 '(yas-field-highlight-face ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#838383") :foreground "black" :background "#D4DCD8"))))
 '(ztreep-diff-model-add-face ((((class color) (min-colors 89)) (:weight bold :foreground "#008800"))))
 '(ztreep-diff-model-diff-face ((((class color) (min-colors 89)) (:weight bold :foreground "#0044DD"))))
 '(ztreep-diff-model-ignored-face ((((class color) (min-colors 89)) (:strike-through t :foreground "#9E9E9E"))))
 '(ztreep-diff-model-normal-face ((((class color) (min-colors 89)) (:foreground "#000000"))))
 '(doom-modeline-evil-insert-state ((t (:inherit (font-lock-keyword-face bold) :foreground "light pink"))))
 '(doom-modeline-buffer-modified ((t (:inherit bold :foreground "light pink"))))
 '(line-number-current-line ((t (:inherit (hl-line line-number)))))
 '(doom-modeline-project-dir ((t (:inherit bold :foreground "DarkOliveGreen2"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#333333" :background "#FFFFFF")))))

(provide-theme 'leuven-high-contrast)
